INSERT INTO `communities` (`title_gr`, `title_en`, `category`, `link`) VALUES
('Τμήμα Μηχανικών Πληροφορικής Και Ηλεκτρονικών Συστημάτων ΔΙΠΑΕ θεσ/νίκης', 'Department of Information and Electronic Engineering I.H.U. Thessalonikis', 'facebook_pages', 'https://www.facebook.com/MixanikonPliroforikisKaiIlektronikonSystimaton/'),
('Ενημέρωση Φοιτητών ΔΙΠΑΕ Σίνδου', 'Inform students I.H.U. Sindos', 'facebook_pages', 'https://www.facebook.com/tei.thessalonikhs/'),
('ΔΙΠΑΕ Μηχανικών Πληροφορικής και Ηλεκτρονικών Συστημάτων', 'I.H.U. Information and Electronic Engineering', 'discord_servers', 'https://discord.gg/9tUnEVMe'),
('ΤΜΗΜΑ ΠΛΗΡΟΦΟΡΙΚΗΣ Α.Τ.Ε.Ι.ΤΗ.', 'A.Τ.Ε.Ι. of Thessaloniki, Department of Information Technology', 'facebook_groups', 'https://www.facebook.com/groups/pliroforikarioi/'),
('ΔΙ.ΠΑ.Ε. - Τμήμα Μηχανικών Πληροφορικής, Υπολογιστών και Τηλεπικοινωνιών', 'I.H.U. - Department of Information and Electronic Engineering', 'facebook_groups', 'https://www.facebook.com/groups/pliroforikiserron/'),
('Περιβαλλοντικη Ομαδα ΔΙΠΑΕ Θεσσαλονικης', 'Environmental group I.H.U Thessalonikis', 'facebook_groups', 'https://www.facebook.com/groups/189405949034962'),
('ΔΙΠΑΕ(Σινδος)', 'I.H.U. (Sindos)', 'facebook_groups', 'https://www.facebook.com/groups/1542744542667713');

INSERT INTO `maps` (`latitude`, `longitude`, `title_gr`, `title_en`, `description_gr`, `description_en`) VALUES
('40.65709541436208', '22.80369452293734', 'Διεθνές Πανεπιστήμιο Ελλάδος - Αλεξανδρεια Πανεπιστημιουπολη', 'International Hellenic University - Alexandria Campus', 'Το πανεπιστήμιο μας.', 'Our university'),
('40.656089735641', '22.804182812928136', 'Τμήμα ΜΠΗΣ - Κτίριο Π', 'Department ΜΠΗΣ - Building Π', 'Τμήμα Μηχανικών Πληροφορικής και Ηλεκτρονικών Συστημάτων - Κτίριο Π', 'Department of Information and Electronic Engineering - Building Π'),
('40.655602367915854', '22.805878923368827', 'Τμήμα ΜΠΗΣ - Κτίριο H', 'Department ΜΠΗΣ - Building Η', 'Τμήμα Μηχανικών Πληροφορικής και Ηλεκτρονικών Συστημάτων - Κτίριο Η', 'Department of Information and Electronic Engineering - Building Η'),
('40.655740736173236', '22.80576627059863', 'Γραμματεία τμήματος ΜΠΗΣ', 'Secretariat of the ΜΠΗΣ department ', 'Γραμματεία τμήματος Μηχανικών Πληροφορικής και Ηλεκτρονικών Συστημάτων', 'Secretariat of the Department of Information and Electronic Engineering');

INSERT INTO `offers` (`title_gr`, `title_en`, `description_gr`, `description_en`, `category`, `link`) VALUES
('Jetbrains', 'Jetbrains', 'Μια μεγάλη συλλογή από προγράμματα για προγραμματιστές με ετήσια άδεια.', 'A large collection of programs for developers with an annual license.', 'softwares', 'https://www.jetbrains.com'),
('Kivuto', 'Kivuto', 'Μια μεγάλη συλλογή από προγράμματα διάφορων εταιριών με πρόσφορες.', 'A large collection of programs of various companies with offers.', 'softwares', 'https://e5.onthehub.com/WebStore/ProductsByMajorVersionList.aspx?ws=be0fe910-869b-e011-969d-0030487d8897'),
('Microsoft', 'Microsoft', 'Μια μεγάλη συλλογή από προγράμματα της Microsoft.', 'A large collection of Microsoft programs. ', 'softwares', 'https://imselab-atei-thessaloniki.weebly.com/ms-azure-gr.html'),
('Github', 'Github', 'Μια μεγάλη συλλογή από συνδρομές και δώρα σε διάφορα προγράμματα και υπηρεσίες.', 'A large collection of subscriptions and gifts in various programs and services. ', 'softwares', 'https://education.github.com');

INSERT INTO `official_services` (`title_gr`, `title_en`, `description_gr`, `description_en`, `category`, `link`) VALUES
('Tμήμα Μηχανικών Πληροφορικής και Ηλεκτρονικών Συστημάτων', 'Department of Information and Electronic Engineering', 'Η ιστοσελίδα του τμήματος.', 'The department website.', 'department', 'https://www.iee.ihu.gr'),
('Moodle', 'Moodle', 'Ο διαδικτυακός χώρος φιλοξενήσεις μαθημάτων.', 'The web site hosting courses. ', 'department', 'https://moodle.teithe.gr/course/index.php?categoryid=125'),
('Moodle Exams', 'Moodle Exams', 'Ο διαδικτυακός χώρος για εξετάσεις μαθημάτων.', 'The web site for course exams. ', 'department', 'https://exams-iee.the.ihu.gr'),
('Ηλεκτρονικό Σύστημα Διπλωματικών', 'Electronic Diplomacy System ', 'Ανάθεση και προβολή διπλωματικών/πτυχιακών.', 'Assignment and view of diplomas/graduates.', 'department', 'https://thesis.iee.ihu.gr'),
('Δηλώσεις Μαθημάτων', 'Course Statements ', 'Δηλώσεις και προβολή μαθημάτων εξαμήνου.', 'Registration and view of semester courses', 'department', 'http://aris.noc.teithe.gr/el/diloseis'),
('Youtube', 'Youtube', 'Το Youtube του τμήματος.', 'YouTube of the department.', 'department', 'https://www.youtube.com/channel/UCq-5LWrceZMl4b5ulXF4RAg'),
('Apps', 'Apps', 'Κύριος λόγος οι ανακοινώσεις του τμήματος.', 'Main reason the announcements of the department.', 'department', 'https://apps.iee.ihu.gr'),
('Feeding', 'Feeding', 'Σύστημα Αιτήσεων Δικαιούχων Δωρεάν Σίτισης.', 'Free Feeding Application System', 'university', 'http://feeding.teithe.gr'),
('Pithia', 'Pithia', 'Κέντρο έλεγχου μαθημάτων και βαθμολόγιων φοιτητή.', 'Student control center for courses and grades.', 'department', 'http://pithia.teithe.gr/unistudent'),
('ECTS 160', 'ECTS 160', 'Έλεγχος για τον αν φοιτητής έχει συμπληρώσει τουλάχιστον 160/210 ΠΜ*', 'Check if student has completed at least 160/210 AM', 'department', 'https://www.iee.ihu.gr/ects160'),
('Διεύθυνση Τεχνικών Υπηρεσιών', 'Technical Services Department ', 'Αιτήσεις έλεγχου/επιδιόρθωσης εγκαταστάσεων και μεγάλες Αίθουσες.', 'Requests to check/repair facilities and large rooms.', 'university', 'http://dty.teithe.gr'),
('Webmail', 'Webmail', 'Το Email του τμήματος.', 'The Email of the department. ', 'department', 'https://webmail.teithe.gr'),
('Πρακτική Άσκηση', 'Internships', 'Η σελίδα για την πρακτική άσκηση των φοιτητών.', 'The student internship page.', 'department', 'http://placements.it.teithe.gr'),
('Κέντρο Δικτύου Αιτήματα', 'Network Center Requests', 'Η σελίδα του κέντρου δεκτού για σχετικά αιτήματα με τους λογαριασμούς.', 'The Admittance Center page for related requests with accounts.', 'university', 'https://helpdesk.the.ihu.gr/index.php'),
('Κεντρική Βιβλιοθήκη Πανεπιστήμιου', 'Central Library of University', 'Μπορείς να αναζητήσεις και βιβλία για αν υπάρχουν.', 'You can search for books if they exist.', 'university', 'https://www.lib.teithe.gr');

INSERT INTO `unofficial_services` (`title_gr`, `title_en`, `description_gr`, `description_en`, `creator_gr`, `creator_en`, `category`, `link`) VALUES
('Φτιάξε το πρόγραμμα του εξαμήνου σου', 'Make your semester schedule', 'Μια προσπάθεια ενός φοιτητή για να διευκολύνει την δημιουργία του εξαμηνιαίου προγράμματος.', 'An effort of a student to facilitate the creation of the semester program. ', 'Νίκος Θεοφανούδης', 'Nikos Theofanoudis ', 'department', 'https://it185181.herokuapp.com');

INSERT INTO `useful_websites` (`title_gr`, `title_en`, `description_gr`, `description_en`, `category`, `link`) VALUES
('Φοιτητικά Νέα', 'Student News', 'Ενημέρωση για όλα τα φοιτητικά νέα.', 'Information for all student news. ', 'news', 'https://www.foititikanea.gr'),
('Eduroam', 'Eduroam', 'Δωρεάν Ίντερνετ στο Campus.', 'Free Internet on Campus. ', 'internet', 'https://www.eduroam.gr'),
('Photomath', 'Photomath', 'Μια mobile εφαρμογή για να λύνεις ασκήσεις με φωτογραφίες.', 'A mobile application to solve exercises with photos.', 'maths', 'https://photomath.com'),
('Symbolab', 'Symbolab', 'Μια ιστοσελίδα για να γράφεις και να λύνεις διάφορες ασκήσεις.', 'A website to write and solve various exercises. ', 'maths', 'https://www.symbolab.com');



INSERT INTO `courses` (`title_gr`, `title_en`, `semester`, `teachers_gr`, `teachers_en`, `link`) VALUES
('Μαθηματικά Ι', 'Mathematics Ι','1o','Αντωνίου Ευστάθιος, Τζέκης Παναγιώτης', 'Antoniou Efstathios, Tzekis Panagiotis', 'course/1101'),
('Δομημένος Προγραμματισμός', 'Structured Programming','1o','Γουλιάνας Κωνσταντίνος, Ουγιάρογλου Στέφανος, Ασδρέ Κατερίνα', 'Goulianas Konstantinos, Ougiaroglou Stefanos, Asdre Katerina','course/1102'),
('Εισαγωγή στην Επιστήμη των Υπολογιστών', 'Introduction to computer science', '1ο', 'Ηλιούδης Χρήστος', 'Ilioudis Christos', 'course/1103'),
('Ηλεκτρονική Φυσική', 'Electronic Physics', '1o', 'Μαρμόρκος Ιωάννης', 'Marmorkos Ioannis', 'course/1104'),
('Κυκλώματα Συνεχούς Ρεύματος', 'DC Circuits', '1o', ' Μπάμνιος Γεώργιος', 'Bamnios Georgios', 'course/1105'),
('Μαθηματικά ΙΙ', 'Mathematics II', '2o', 'Αντωνίου Ευστάθιος, Τζέκης Παναγιώτης', 'Antoniou Efstathios, Tzekis Panagiotis', 'course/1201'),
('Μετρήσεις και Κυκλώματα Εναλλασσόμενου Ρεύματος', ' Measurements and Alternating Current Circuits', '2o', 'Κιοσκερίδης Ιορδάνης, Χατζόπουλος Αργύριος, Αμπατζής Ζαφείριος, Παπαδοπούλου Μαρία', 'Kioskeridis Iordanis, Chatzopoulos Argyrios, Ampatzis Zafeirios, Papadopoulou Maria', 'course/1202'),
('Τεχνική Συγγραφή, Παρουσίαση και Ορολογία Ξένης Γλώσσας', 'Technical Writing, Presentation and Terminology of Foreign Language', '2o', 'Χατζημίσιος Περικλής, Αγγέλου Κωνσταντίνος, Καζακόπουλος Αριστοτέλης', 'Chatzimisios Periklis, Angelou Konstantinos, Kazakopoulos Aristotelis', 'course/1203'),
('Σχεδίαση Ψηφιακών Συστημάτων', 'Digital System Design', '2o', 'Μπάμνιος Γεώργιος, Τσιακμάκης Κυριάκος', 'Bamnios Georgios, Tsiakmakis Kyriakos', 'course/1204'),
('Αντικειμενοστρεφής Προγραμματισμός', 'Object Oriented Programming', '2o', 'Δεληγιάννης Ιγνάτιος, Αδαμίδης Παναγιώτης', 'Deligiannis Ignatios, Adamidis Panagiotis', 'course/1205'),
('Θεωρία Πιθανοτήτων και Στατιστική', 'Probability Theory and Statistics', '3o', 'Τζέκης Παναγιώτης', 'Tzekis Panagiotis', 'course/1301'),
('Μαθηματικά ΙΙΙ', 'Mathematics ΙΙI', '3o', 'Αντωνίου Ευστάθιος', 'Antoniou Efstathios', 'course/1302'),
('Επεξεργασία Σήματος', 'Signal Processing', '3o', 'Αβδελίδης Κωνσταντίνος', 'Avdelidis Konstantinos', 'course/1303'),
('Γλώσσες και Τεχνολογίες Ιστού', 'Web Languages and Technologies', '3o', 'Σαλαμπάσης Μιχάλης, Ασδρέ Κατερίνα', 'Salampasis Michalis, Asdre Katerina', 'course/1405'),
('Δομές Δεδομένων και Ανάλυση Αλγορίθμων', 'Data Structures and Analysis of Algorithms', '3o', 'Αδαμίδης Παναγιώτης, Ασδρέ Κατερίνα, Σταμάτης Δημοσθένης', 'Adamidis Panagiotis, Asdre Katerina, Stamatis Dimosthenis', 'course/1305'),
('Οργάνωση και Αρχιτεκτονική Υπολογιστικών Συστημάτων', 'Computer System Organization and Architecture', '4o', 'Διαμαντάρας Κωνσταντίνος, Αμανατιάδης Δημήτριος', 'Diamantaras Konstantinos, Amanatiadis Dimitrios', 'course/1304'),
('Συστήματα Διαχείρισης Βάσεων Δεδομένων', 'Database Management Systems', '4o', 'Δέρβος Δημήτριος, Ουγιάρογλου Στέφανος', 'Dervos Dimitrios, Ougiaroglou Stefanos', 'course/1401'),
('Τηλεπικοινωνιακά Συστήματα', 'Telecommunication Systems', '4o', 'Ιωαννίδου Μελίνα, Ιωσηφίδης Αθανάσιος', 'Ioannidou Melina, Iosifidis Athanasios', 'course/1402'),
('Εισαγωγή στα Λειτουργικά Συστήματα', 'Introduction to Operating Systems', '4o', 'Σιδηρόπουλος Αντώνης, Καπλάνογλου Παντελής, Μπαργούλη Μαρίσα', 'Sidiropoulos Antonis, Kaplanoglou Pantelis, Bargouli Marisa', 'course/1403'),
('Ηλεκτρονικά Κυκλώματα', 'Electronic Circuits', '4o', 'Παπακώστας Δημήτριος, Χατζόπουλος Αργύριος', 'Papakostas Dimitrios, Chatzopoulos Argyrios', 'course/1404'),
('Ασύρματες Επικοινωνίες', 'Wireless Communications', '5o', 'Ιωαννίδου Μελίνα, Ιωσηφίδης Αθανάσιος, Αμπατζής Ζαφείριος', 'Ioannidou Melina, Iosifidis Athanasios, Ampatzis Zafeirios', 'course/1501'),
('Μικροελεγκτές', 'Microcontrollers', '5o', 'Καζακόπουλος Αριστοτέλης, Σαπουνίδης Θεοδόσιος', 'Kazakopoulos Aristotelis, Sapounidis Theodosios', 'course/1502'),
('Σχεδίαση Λειτουργικών Συστημάτων', 'Operating Systems Design', '5o', 'Ουγιάρογλου Στέφανος, Δεληγιάννης Ιγνάτιος', 'Ougiaroglou Stefanos, Deligiannis Ignatios', 'course/1503'),
('Ηλεκτρονικές Διατάξεις', 'Electronic Devices', '5o', 'Παπακώστας Δημήτριος, Χατζόπουλος Αργύριος, Τσιακμάκης Κυριάκος', 'Papakostas Dimitrios, Chatzopoulos Argyrios, Tsiakmakis Kyriakos', 'course/1504'),
('Αλληλεπίδραση Ανθρώπου-Μηχανής', 'Human Machine Interaction', '5o', 'Κεραμόπουλος Ευκλείδης', 'Keramopoulos Efkleidis', 'course/1505'),
('Τεχνητή Νοημοσύνη', 'Artificial Intelligence', '6o', 'Σταμάτης Δημοσθένης', 'Stamatis Dimosthenis', 'course/1601'),
('Ενσωματωμένα Συστήματα', 'Embedded Systems', '6o', 'Καζακόπουλος Αριστοτέλης, Γιακουμής Άγγελος', 'Kazakopoulos Aristotelis, Giakoumis Angelos', 'course/1602'),
('Σύνθεση Ηλεκτρονικών Κυκλωμάτων', 'Synthesis of electronic circuits', '6o', 'Σπάσος Μιχαήλ', 'Spasos Michail', 'course/1611'),
('Κβαντική Υπολογιστική', 'Quantum Computing', '6o', 'Μαρμόρκος Ιωάννης', 'Marmorkos Ioannis', 'course/1612'),
('Μεθοδολογίες Σχεδιασμού Μικροηλεκτρονικών Κυκλωμάτων', 'Microelectronic Circuit Design Methodologies', '6o', 'Παπακώστας Δημήτριος', 'Papakostas Dimitrios', 'course/1613'),
('Μικροκυματική Τεχνολογία και Τηλεπισκόπηση', 'Microwave Technology and Remote Sensing', '6o', 'Ιωαννίδου Μελίνα', 'Ioannidou Melina', 'course/1671'),
('Οπτοηλεκτρονική και Οπτικές Επικοινωνίες', 'Optoelectronics and Optical Communications', '6o', 'Μαρμόρκος Ιωάννης', 'Marmorkos Ioannis', 'course/1672'),
('Συστήματα Μέσων Μαζικής Επικοινωνίας', 'Mass Media Systems', '6o', 'null', 'null', 'course/1673'),
('Αριθμητικές Μέθοδοι', 'Numerical Methods', '6o', 'Γουλιάνας Κωνσταντίνος', 'Goulianas Konstantinos', 'course/1641'),
('Προηγμένα Θέματα Αλληλεπίδρασης (Προγραμματισμός Κινητών Συσκευών)', 'Advanced Topics of Human Computer Interaction (Mobile Programming)', '6o', 'Κεραμόπουλος Ευκλείδης', 'Keramopoulos Efkleidis', 'course/1642'),
('Διοίκηση Έργων', 'Project Management', '6o', 'Κώστογλου Βασίλης', 'Kostoglou Vasilis', 'course/1643'),
('Δίκτυα Υπολογιστών', 'Computer Networks', '7o', 'Βίτσας Βασίλης, Αμανατιάδης Δημήτριος', 'Vitsas Vasilis, Amanatiadis Dimitrios', 'course/1701'),
('Ηλεκτρονικά Ισχύος', 'Power Electronics', '7o', 'Κιοσκερίδης Ιορδάνης', 'Kioskeridis Iordanis', 'course/1702'),
('Συστήματα Αυτομάτου Ελέγχου', 'Automatic control system', '7o', 'Τζέκης Παναγιώτης, Τσιριγώτης Γεώργιος', 'Tzekis Panagiotis, Tsirigotis Georgios', 'course/1711'),
('Αισθητήρια και Επεξεργασία Μετρήσεων', 'Sensors Signal Contitioning', '7o', 'Σπάσος Μιχαήλ', 'Spasos Michail', 'course/1712'),
('Προγραμματιζόμενοι Λογικοί Ελεγκτές', 'Programmable Logic Controllers', '7o', 'Μανάβης Χρήστος, Τζέκης Παναγιώτης', 'Manavis Christos, Tzekis Panagiotis', 'course/1713'),
('Σχεδίαση Επαναπροσδιοριζόμενων Ψηφιακών Συστημάτων (FPGA)', 'Design of Reconfigurable Digital Systems (FPGAs)', '7o', 'Παπακώστας Δημήτριος', 'Papakostas Dimitrios', 'course/1714'),
('Τεχνολογίες Ήχου και Εικόνας', 'Audio and Video Technologies', '7o', 'null', 'null', 'course/1771'),
('Εισαγωγή στην Αναλυτική των Δεδομένων', 'Introduction to Data Analytics', '7o', 'Δέρβος Δημήτριος', 'Dervos Dimitrios', 'course/1741'),
('Μηχανική Λογισμικού', 'Software Engineering', '7o', 'Δεληγιάννης Ιγνάτιος', 'Deligiannis Ignatios', 'course/1742'),
('Τεχνολογία Βάσεων Δεδομένων', 'Database Technology', '7o', 'Δέρβος Δημήτριος, Κεραμόπουλος Ευκλείδης', 'Dervos Dimitrios, Keramopoulos Efkleidis', 'course/1743'),
('Προηγμένες Αρχιτεκτονικές Υπολογιστών και Προγραμματισμός Παράλληλων Συστημάτων', 'Advanced Computer Architecture and Parallel System Programming', '7o', 'Διαμαντάρας Κωνσταντίνος', 'Diamantaras Konstantinos', 'course/1744'),
('Ασφάλεια Πληροφοριακών Συστημάτων', 'Information Security', '8o', 'Ηλιούδης Χρήστος, Μπαλτατζής Δημήτριος', 'Ilioudis Christos, Balatzis Dimitrios', 'course/1801'),
('Αρχές και Μέθοδοι Μηχανικής Μάθησης', 'Machine Learning Principles and Methods', '8o', 'Γουλιάνας Κωνσταντίνος, Διαμαντάρας Κωνσταντίνος', 'Goulianas Konstantinos, Diamantaras Konstantinos', 'course/1802'),
('Διαδίκτυο των Πραγμάτων', 'Internet of Things', '8o', 'Χατζημίσιος Περικλής, Ηλιούδης Χρήστος', 'Chatzimisios Periklis, Ilioudis Christos', 'course/1803'),
('Εφαρμογές Συστημάτων Αυτομάτου Ελέγχου', 'Automatic Control Systems Applications', '8o', 'Μανάβης Χρήστος, Τζέκης Παναγιώτης', 'Manavis Christos, Tzekis Panagiotis', 'course/1811'),
('Μετατροπείς Ισχύος', 'Power Converters', '8o', 'Κιοσκερίδης Ιορδάνης', 'Kioskeridis Iordanis', 'course/1812'),
('Μικροηλεκτρονική', 'Microelectronics', '8o', 'null', 'null', 'course/1837'),
('Εφαρμογές Συστημάτων Ισχύος και ΑΠΕ', 'Application of power systems and RES', '8o', 'null', 'null', 'course/1838'),
('Ηλεκτροκίνηση και Ευφυή Δίκτυα', 'Motor drives and smart grid', '8o', 'null', 'null', 'course/1839'),
('Ασύρματα Δίκτυα', 'Wireless networks', '8o', 'Ιωσηφίδης Αθανάσιος, Βίτσας Βασίλης', 'Iosifidis Athanasios, Vitsas Vasilis', 'course/1871'),
('Ειδικά Θέματα Δικτύων (CCNA) 1', 'Special Network Topics (CCNA) 1', '8o', 'Βίτσας Βασίλης, Σαρηγιαννίδης Αντώνης', 'Vitsas Vasilis, Sarigiannidis Antonis', 'course/1872'),
('Προηγμένα Θέματα Δικτύων', 'Advanced Network ThemesΒίτσας Βασίλης', '8o', 'Βίτσας Βασίλης', 'Vitsas Vasilis', 'course/1873'),
('Συστήματα Κινητών Επικοινωνιών', 'Mobile Communication Systems', '8o', 'Ιωσηφίδης Αθανάσιος', 'Iosifidis Athanasios', 'course/1874'),
('Ελεύθερη Επιλογή Β', 'Free Selection B', '8o', 'null', 'null', 'course/1898'),
('Ραδιοτηλεοπτική Παραγωγή', 'Broadcast Production', '8o', 'null', 'null', 'course/1899'),
('Οργάνωση Δεδομένων και Εξόρυξη Πληροφορίας', 'Data Organization and Data Mining', '8o', 'Δέρβος Δημήτριος, Ουγιάρογλου Στέφανος', 'Dervos Dimitrios, Ougiaroglou Stefanos', 'course/1841'),
('Διαδικτυακές Υπηρεσίες Προστιθέμενης Αξίας', 'Added-Value Internet Services', '8o', 'Σαλαμπάσης Μιχάλης', 'Salampasis Michalis', 'course/1842'),
('Ανάπτυξη Ολοκληρωμένων Πληροφοριακών Συστημάτων', 'Development of Large Software Systems', '8o', 'Σαλαμπάσης Μιχάλης', 'Salampasis Michalis', 'course/1848'),
('Πρακτική Άσκηση', 'Internship', '9o', 'Γουλιάνας Κωνσταντίνος', 'Goulianas Konstantinos', 'course/1970'),
('Εφαρμογές Ενσωματωμένων Συστημάτων', 'Applications of Embedded Systems', '9o', 'Γιακουμής Άγγελος, Καζακόπουλος Αριστοτέλης', 'Giakoumis Angelos, Kazakopoulos Aristotelis', 'course/1911'),
('Ρομποτική', 'Robotics', '9o', 'Παπαγεωργίου Δημήτριος, Σαπουνίδης Θεοδόσιος', 'Papageorgiou Dimitrios, Sapounidis Theodosios', 'course/1912'),
('ΑΠΕ και Ευφυή Ηλεκτρικά Δίκτυα', 'Renewable energy sources and smart grid', '9o', 'Κιοσκερίδης Ιορδάνης', 'Kioskeridis Iordanis', 'course/1913'),
('Απτικές Διεπαφές', 'Tangible User Interfaces', '9o', 'Σαπουνίδης Θεοδόσιος', 'Sapounidis Theodosios', 'course/1914'),
('Βιοϊατρική Τεχνολογία', 'Biomedical Technology', '9o', 'Καζακόπουλος Αριστοτέλης', 'Kazakopoulos Aristotelis', 'course/1915'),
('Συστήματα Μετρήσεων Υποβοηθούμενων από Η/Υ', 'Computer Assisted Measurement Systems', '9o', 'Χατζόπουλος Αργύριος', 'Chatzopoulos Argyrios', 'course/1916'),
('Ασφάλεια Δικτύων και Επικοινωνιών', 'Network and Communication Security', '9o', 'Ηλιούδης Χρήστος', 'Ilioudis Christos', 'course/1971'),
('Δικτύωση Καθορισμένη από Λογισμικό', 'Software Defined Networking', '9o', 'Ιωαννίδου Μελίνα, Χατζημίσιος Περικλής', 'Ioannidou Melina, Chatzimisios Periklis', 'course/1972'),
('Ειδικά Θέματα Δικτύων (CCNA) 2', 'Special Network Topics (CCNA) 2', '9o', 'Βίτσας Βασίλης, Σαρηγιαννίδης Αντώνης', 'Vitsas Vasilis, Sarigiannidis Antonis', 'course/1973'),
('Δορυφορικές Επικοινωνίες', 'Satellite Communications', '9o', 'Μαρμόρκος Ιωάννης', 'Marmorkos Ioannis', 'course/1974'),
('Τεχνολογία Πολυμέσων', 'Multimedia Technology', '9o', 'Βολιώτη Χριστίνα', 'Volioti Christina', 'course/1975'),
('Ελεύθερη Επιλογή Α', 'Free Selection A', '9o', 'null', 'null', 'course/1998'),
('Ανάπτυξη Διαδικτυακών Συστημάτων και Εφαρμογών', 'Development of Web Systems and Applications', '9o', 'Ουγιάρογλου Στέφανος, Σιδηρόπουλος Αντώνης', 'Ougiaroglou Stefanos, Sidiropoulos Antonis', 'course/1941'),
('Επιχειρησιακή Έρευνα', 'Operational Research', '9o', 'Κώστογλου Βασίλης', 'Kostoglou Vasilis', 'course/1942'),
('Ανάκτηση Πληροφοριών – Μηχανές Αναζήτησης', 'Information Retrieval – Search Engines', '9o', 'Σαλαμπάσης Μιχάλης', 'Salampasis Michalis', 'course/1943'),
('Διαχείριση Συστήματος και Υπηρεσιών DBMS', 'DBMS Systems and Services Administration', '9o', 'Δέρβος Δημήτριος, Σιδηρόπουλος Αντώνης', 'Dervos Dimitrios, Sidiropoulos Antonis', 'course/1944'),
('Ευφυή Συστήματα', 'Intelligent Systems', '9o', 'Αδαμίδης Παναγιώτης', 'Adamidis Panagiotis', 'course/1945'),
('Προηγμένα Θέματα Τεχνητής Νοημοσύνης', 'Artificial Intelligence – Advanced Topics', '9o', 'Σταμάτης Δημοσθένης', 'Stamatis Dimosthenis', 'course/1946'),
('Προηγμένη Μηχανική Μάθηση', 'Advanced Machine Learning', '9o', 'Διαμαντάρας Κωνσταντίνος', 'Diamantaras Konstantinos', 'course/1947'),
('Κατανεμημένα Συστήματα', 'Distributed Systems', '9o', 'Σιδηρόπουλος Αντώνης, Ακριτίδης Λεωνίδας, Διαμαντάρας Κωνσταντίνος', 'Sidiropoulos Antonis, Akritidis Leonidas, Diamantaras Konstantinos', 'course/1949'),
('Σημασιολογικός Ιστός', 'Semantic Web', '9o', 'Αδαμίδης Παναγιώτης, Κεραμόπουλος Ευκλείδης', 'Adamidis Panagiotis, Keramopoulos Efkleidis', 'course/1950'),
('Γραφικά Υπολογιστών', 'Computer Graphics', '9o', 'Κεραμόπουλος Ευκλείδης, Βολιώτη Χριστίνα', 'Keramopoulos Efkleidis, Volioti Christina', 'course/1969'),
(' Διπλωματική Εργασία', 'Thesis', '10o', 'null', 'null', 'course/1999');

INSERT INTO `teachers` (`name_gr`, `name_en`, `email`, `personal_site`, `category_gr`, `category_en`, `link`) VALUES
('Αδαμίδης Παναγιώτης', 'Adamidis Panagiotis', 'adamidis@it.teithe.gr', 'https://people.iee.ihu.gr/~adamidis/', 'Μέλη Δ.Ε.Π.', 'Faculty Members', 'https://www.iee.ihu.gr/staff/adamidis-panagiotis/'),
('Βίτσας Βασίλης', 'Vitsas Vasilis', 'vitsas@it.teithe.gr', 'https://www.it.teithe.gr/~vitsas', 'Μέλη Δ.Ε.Π.', 'Faculty Members', 'https://www.iee.ihu.gr/staff/vitsas-vasilis/'),
('Δεληγιάννης Ιγνάτιος', 'Deligiannis Ignatios', 'ignatios@it.teithe.gr', 'null', 'Μέλη Δ.Ε.Π.', 'Faculty Members', 'https://www.iee.ihu.gr/staff/deligiannis-ignatios/'),
('Δέρβος Δημήτριος', 'Dervos Dimitrios', 'dad@it.teithe.gr', 'https://www.iee.ihu.gr/~dad', 'Μέλη Δ.Ε.Π.', 'Faculty Members', 'https://www.iee.ihu.gr/staff/dervos-dimitrios/'),
('Διαμαντάρας Κωνσταντίνος', 'Diamantaras Konstantinos', 'k.diamantaras@ihu.edu.gr', 'https://www.iee.ihu.gr/~kdiamant', 'Μέλη Δ.Ε.Π', 'Faculty Members', 'https://www.iee.ihu.gr/staff/diamantaras-konstantinos/'),
('Ηλιούδης Χρήστος', 'Ilioudis Christos', 'iliou@it.teithe.gr', 'https://www.it.teithe.gr/~iliou', 'Μέλη Δ.Ε.Π.', 'Faculty Members', 'https://www.iee.ihu.gr/staff/ilioudis-christos/'),
('Καζακόπουλος Αριστοτέλης', 'Kazakopoulos Aristotelis', 'kazak@el.teithe.gr', 'null', 'Μέλη Δ.Ε.Π.', 'Faculty Members', 'https://www.iee.ihu.gr/staff/kazakopoulos-aristotelis/'),
('Κιοσκερίδης Ιορδάνης', 'Kioskeridis Iordanis', 'ikiosker@ihu.gr', 'null', 'Μέλη Δ.Ε.Π.', 'Faculty Members', 'https://www.iee.ihu.gr/staff/kioskeridis-iordanis/'),
('Κώστογλου Βασίλειος', 'Kostoglou Vasilis', 'vkostogl@ihu.gr', 'https://people.iee.ihu.gr/~vkostogl/', 'Μέλη Δ.Ε.Π.', 'Faculty Members', 'https://www.iee.ihu.gr/staff/kostoglou-vasileios/'),
('Μαρμόρκος Ιωάννης', 'Marmorkos Ioannis', 'imarm@el.teithe.gr', 'null', 'Μέλη Δ.Ε.Π.', 'Faculty Members', 'https://www.iee.ihu.gr/staff/marmorkos-ioannis/'),
('Μπάμνιος Γεώργιος', 'Bamnios Georgios', 'bamnios@el.teithe.gr', 'null', 'Μέλη Δ.Ε.Π.', 'Faculty Members', 'https://www.iee.ihu.gr/staff/bamnios-georgios/'),
('Παπακώστας Δημήτριος', 'Papakostas Dimitrios', 'dpapakos@ihu.gr', 'null', 'Μέλη Δ.Ε.Π.', 'Faculty Members', 'https://www.iee.ihu.gr/staff/papakostas-dimitrios/'),
('Σαλαμπάσης Μιχάλης', 'Salampasis Michalis', 'msa@ihu.gr', 'https://www.salampasis.gr', 'Μέλη Δ.Ε.Π.', 'Faculty Members', 'https://www.iee.ihu.gr/staff/salampasis-michalis/'),
('Σταμάτης Δημοσθένης', 'Stamatis Dimosthenis', 'demos@it.teithe.gr', 'https://www.it.teithe.gr/~demos', 'Μέλη Δ.Ε.Π', 'Faculty Members', 'https://www.iee.ihu.gr/staff/stamatis-dimosthenis/'),
('Χατζημίσιος Περικλής', 'Chatzimisios Periklis', 'pchatzimisios@ihu.gr', 'https://people.iee.ihu.gr/~peris/', 'Μέλη Δ.Ε.Π.', 'Faculty Members', 'https://www.iee.ihu.gr/staff/chatzimisios-periklis/'),
('Αντωνίου Ευστάθιος', 'Antoniou Efstathios', 'antoniou@ihu.gr', 'https://www.iee.ihu.gr/~antoniou/', 'Μέλη Δ.Ε.Π.', 'Faculty Members', 'https://www.iee.ihu.gr/staff/antoniou-efstathios/'),
('Γουλιάνας Κωνσταντίνος', 'Goulianas Konstantinos', 'gouliana@it.teithe.gr', 'https://aetos.it.teithe.gr/~gouliana/', 'Μέλη Δ.Ε.Π.', 'Faculty Members', 'https://www.iee.ihu.gr/staff/goulianas-konstantinos/'),
('Ιωαννίδου Μελίνα', 'Ioannidou Melina', 'melina@ihu.gr', 'null', 'Μέλη Δ.Ε.Π.', 'Faculty Members', 'https://www.iee.ihu.gr/staff/ioannidou-melina/'),
('Ιωσηφίδης Αθανάσιος', 'Iosifidis Athanasios', 'aiosifidis@el.teithe.gr', 'null', 'Μέλη Δ.Ε.Π.', 'Faculty Members', 'https://www.iee.ihu.gr/staff/iosifidis-athanasios/'),
('Κεραμόπουλος Ευκλείδης', 'Keramopoulos Efkleidis', 'euclid@it.teithe.gr', 'https://people.iee.ihu.gr/~euclid/', 'Μέλη Δ.Ε.Π.', 'Faculty Members', 'https://www.iee.ihu.gr/staff/keramopoulos-efkleidis/'),
('Σπάσος Μιχαήλ', 'Spasos Michail', 'spasos@el.teithe.gr', 'null', 'Μέλη Δ.Ε.Π.', 'Faculty Members', 'https://www.iee.ihu.gr/staff/spasos-michail/'),
('Τζέκης Παναγιώτης', 'Tzekis Panagiotis', 'ptzekis@el.teithe.gr', 'https://aetos.it.teithe.gr/~ptzekis/', 'Μέλη Δ.Ε.Π.', 'Faculty Members', 'https://www.iee.ihu.gr/staff/tzekis-panagiotis/'),
('Κωτσάκης Ρήγας', 'Kotsakis Rigas', 'rkotsakis@gmail.com', 'null', 'Μέλη Δ.Ε.Π.', 'Faculty Members', 'https://www.iee.ihu.gr/staff/kotsakis-rigas/'),
('Σαπουνίδης Θεοδόσιος', 'Sapounidis Theodosios', 'sapounidis@ihu.gr', 'null', 'Μέλη Δ.Ε.Π.', 'Faculty Members', 'https://www.iee.ihu.gr/staff/sapounidis-theodosios/'),
('Σιδηρόπουλος Αντώνης', 'Sidiropoulos Antonis', 'asidirop@gmail.com', 'https://people.iee.ihu.gr/~asidirop/', 'Μέλη Δ.Ε.Π.', 'Faculty Members', 'https://www.iee.ihu.gr/staff/sidiropoulos-antonis-2/'),
('Χατζόπουλος Αργύριος', 'Chatzopoulos Argyrios', 'ahatz@ihu.gr', 'null', 'Μέλη Δ.Ε.Π.', 'Faculty Members', 'https://www.iee.ihu.gr/staff/chatzopoulos-argyrios/'),
('Γιακουμής Άγγελος', 'Giakoumis Angelos', 'ang1960@el.teithe.gr', 'null', 'Μέλη Δ.Ε.Π.', 'Faculty Members', 'https://www.iee.ihu.gr/staff/giakoumis-angelos/'),
('Μανάβης Χρήστος', 'Manavis Christos', 'null', 'null', 'Μέλη Δ.Ε.Π.', 'Faculty Members', 'https://www.iee.ihu.gr/staff/manavis-christos/'),
('Μπαλτατζής Δημήτριος', 'Baltatzis Dimitrios', 'null', 'null', 'Μέλη Δ.Ε.Π. άλλων τμήματων', 'Visiting Faculty Members', 'https://www.iee.ihu.gr/staff/tsirigotis-georgios/'),
('Τσιριγώτης Γεώργιος', 'Tsirigotis Georgios', 'null', 'null', 'Μέλη Δ.Ε.Π. άλλων τμήματων', 'Visiting Faculty Members', 'https://www.iee.ihu.gr/staff/tsirigotis-georgios/'),
('Αγγέλου Κωνσταντίνος', 'Angelou Konstantinos', 'kagel@admin.teithe.gr', 'null', 'Προσωπικό Ε.ΔΙ.Π.', 'Laboratory Associates ', 'https://www.iee.ihu.gr/staff/angelou-konstantinos/'),
('Αμανατιάδης Δημήτριος', 'Amanatiadis Dimitrios', 'dima@it.teithe.gr', 'https://people.iee.ihu.gr/~dima/', 'Προσωπικό Ε.ΔΙ.Π.', 'Laboratory Associates', 'https://www.iee.ihu.gr/staff/amanatiadis-dimitrios/'),
('Αμπατζής Ζαφείριος', 'Ampatzis Zafeirios', 'zafiris@el.teithe.gr', 'null', 'Προσωπικό Ε.ΔΙ.Π', 'Laboratory Associates', 'https://www.iee.ihu.gr/staff/ampatzis-zafeirios/'),
('Ασδρέ Κατερίνα', 'Asdre Katerina', 'asdre@it.teithe.gr', 'null', 'Προσωπικό Ε.ΔΙ.Π.', 'Laboratory Associates', 'https://www.iee.ihu.gr/staff/asdre-katerina/'),
('Καλλιδοπούλου Άννα-Ελένη', 'Kallidopoulou Anna-Eleni', 'null', 'null', 'Προσωπικό Ε.ΔΙ.Π.', 'Laboratory Associates ', 'https://www.iee.ihu.gr/staff/kallidopoulou-anna-eleni/'),
('Ουγιάρογλου Στέφανος', 'Ougiaroglou Stefanos', 'stoug@ihu.gr', 'https://www.iee.ihu.gr/~stoug', 'Προσωπικό Ε.ΔΙ.Π.', 'Laboratory Associates', 'https://www.iee.ihu.gr/staff/ougiaroglou-stefanos/'),
('Τσιακμάκης Κυριάκος', 'Tsiakmakis Kyriakos', 'ktsiak@physics.auth.gr', 'https://aetos.it.teithe.gr/~ktsiak/', 'Προσωπικό Ε.ΔΙ.Π.', 'Laboratory Associates', 'https://www.iee.ihu.gr/staff/tsiakmakis-kyriakos/'),
('Αβδελίδης Κωνσταντίνος', 'Avdelidis Konstantinos', 'null', 'null', 'Έκτακτο Εκπαιδευτικό Προσωπικό', 'Visiting Lecturers', 'https://www.iee.ihu.gr/staff/avdelidis-konstantinos/'),
('Ακριτίδης Λεωνίδας', 'Akritidis Leonidas', 'lakritidis@ihu.gr', 'https://people.iee.ihu.gr/~lakritidis/', 'Έκτακτο Εκπαιδευτικό Προσωπικό', 'Visiting Lecturers', 'https://www.iee.ihu.gr/staff/akritidis-leonidas/'),
('Αλεξούδη Θεόνη', 'Alexoudi Theoni', 'theoni.alex@gmail.com', 'null', 'Έκτακτο Εκπαιδευτικό Προσωπικό', 'Visiting Lecturers', 'https://www.iee.ihu.gr/staff/alexoudi-theoni/'),
('Αρβανίτου Ελβίρα Μαρία', 'Arvanitou Elvira Maria', 'null', 'null', 'Έκτακτο Εκπαιδευτικό Προσωπικό', 'Visiting Lecturers ', 'https://www.iee.ihu.gr/staff/arvanitou-elvira-maria/'),
('Βάσσιος Βασίλειος', 'Vassios Vasileios', 'null', 'null', 'Έκτακτο Εκπαιδευτικό Προσωπικό', 'Visiting Lecturers', 'https://www.iee.ihu.gr/staff/vassios-vasileios/'),
('Βολιώτη Χριστίνα', 'Volioti Christina', 'null', 'null', 'Έκτακτο Εκπαιδευτικό Προσωπικό', 'Visiting Lecturers', 'https://www.iee.ihu.gr/staff/volioti-christina/'),
('Γεωργούδας Ιωακείμ', 'Georgoudas Ioakeim', 'mgeorgoudas@gmail.com', 'null', 'Έκτακτο Εκπαιδευτικό Προσωπικό', 'Visiting Lecturers', 'https://www.iee.ihu.gr/staff/georgoudas-ioakeim/'),
('Δελημαράς Βασίλειος', 'Delimaras Vasileios', 'null', 'null', 'Έκτακτο Εκπαιδευτικό Προσωπικό', 'Visiting Lecturers', 'https://www.iee.ihu.gr/staff/delimaras-vasileios/'),
('Δημητριάδης Παναγιώτης', 'Dimitriadis Panagiotis', 'panosdimel@gmail.com', 'null', 'Έκτακτο Εκπαιδευτικό Προσωπικό', 'Visiting Lecturers', 'https://www.iee.ihu.gr/staff/dimitriadis-panagiotis/'),
('Διαμαντουλάκης Παναγιώτης', 'Diamantoulakis Panagiotis', 'null', 'null', 'Έκτακτο Εκπαιδευτικό Προσωπικό', 'Visiting Lecturers', 'https://www.iee.ihu.gr/staff/diamantoulakis-panagiotis/'),
('Καπλάνογλου Παντελής', 'Kaplanoglou Pantelis', 'pikaplanoglou@it.teithe.gr', 'null', 'Έκτακτο Εκπαιδευτικό Προσωπικό', 'Visiting Lecturers', 'https://www.iee.ihu.gr/staff/kaplanoglou-pantelis/'),
('Κασδερίδης Στάθης', 'Kasderidis Stathis', 'kas-ihu@novocaptis.com', 'null', 'Έκτακτο Εκπαιδευτικό Προσωπικό', 'Visiting Lecturers', 'https://www.iee.ihu.gr/staff/kasderidis-stathis/'),
('Λαμπρόπουλος Γεώργιος', 'Lampropoulos Georgios', 'glampropoulos@it.teithe.gr', 'null', 'Έκτακτο Εκπαιδευτικό Προσωπικό', 'Visiting Lecturers', 'https://www.iee.ihu.gr/staff/lampropoulos-georgios/'),
('Μεσοδιακάκη Αγάπη', 'Mesodiakaki Agapi', 'null', 'https://sites.google.com/site/agapimesodiakaki', 'Έκτακτο Εκπαιδευτικό Προσωπικό', 'Visiting Lecturers', 'https://www.iee.ihu.gr/staff/mesodiakaki-agapi/'),
('Μηλιώτης Βασίλης', 'Miliotis Vasilis', 'null', 'null', 'Έκτακτο Εκπαιδευτικό Προσωπικό', 'Visiting Lecturers', 'https://www.iee.ihu.gr/staff/miliotis-vasilis/'),
('Μπαργούλη Μαρίσα', 'Bargouli Marisa', 'null', 'null', 'Έκτακτο Εκπαιδευτικό Προσωπικό', 'Visiting Lecturers', 'https://www.iee.ihu.gr/staff/bargouli-marisa/'),
('Παπαγεωργίου Δημήτριος', 'Papageorgiou Dimitrios', 'dimpapag@ece.auth.gr', 'https://arl.ee.auth.gr/people/papageorgiou', 'Έκτακτο Εκπαιδευτικό Προσωπικό', 'Visiting Lecturers', 'https://www.iee.ihu.gr/staff/papageorgiou-dimitrios/'),
('Παπαδοπούλου Μαρία', 'Papadopoulou Maria', 'mpapa@el.teithe.gr', 'null', 'Έκτακτο Εκπαιδευτικό Προσωπικό', 'Visiting Lecturers', 'https://www.iee.ihu.gr/staff/papadopoulou-maria/'),
('Σαρηγιαννίδης Αντώνης', 'Sarigiannidis Antonis', 'null', 'null', 'Έκτακτο Εκπαιδευτικό Προσωπικό', 'Visiting Lecturers', 'https://www.iee.ihu.gr/staff/sarigiannidis-antonis/'),
('Τεκτονίδης Δημήτριος', 'Tektonidis Dimitrios', 'null', 'null', 'Έκτακτο Εκπαιδευτικό Προσωπικό', 'Visiting Lecturers ', 'https://www.iee.ihu.gr/staff/tektonidis-dimitrios/'),
('Τοκατλίδης Χρήστος', 'Tokatlidis Christos', 'dtektoni@it.teithe.gr', 'https://aetos.it.teithe.gr/~dtektoni', 'Έκτακτο Εκπαιδευτικό Προσωπικό', 'Visiting Lecturers', 'https://www.iee.ihu.gr/staff/tokatlidis-christos/'),
('Τσελεγκαρίδης Σωκράτης', 'Tselegkaridis Sokratis', 'sok.tsele@gmail.com', 'null', 'Έκτακτο Εκπαιδευτικό Προσωπικό', 'Visiting Lecturers', 'https://www.iee.ihu.gr/staff/tselegkaridis-sokratis/'),
('Τσιρογιάννης Ανδρέας', 'Tsirogiannis Andreas', 'null', 'null', 'Έκτακτο Εκπαιδευτικό Προσωπικό', 'Visiting Lecturers ', 'https://www.iee.ihu.gr/staff/tsirogiannis-andreas/');
