INSERT INTO `communities` (`title_gr`, `title_en`, `category`, `link`) VALUES
('Τμήμα Μηχανικών Πληροφορικής Και Ηλεκτρονικών Συστημάτων ΔΙΠΑΕ θεσ/νίκης', 'Department of Information and Electronic Engineering I.H.U. Thessalonikis', 'facebook_pages', 'https://www.facebook.com/MixanikonPliroforikisKaiIlektronikonSystimaton/'),
('Ενημέρωση Φοιτητών ΔΙΠΑΕ Σίνδου', 'Inform students I.H.U. Sindos', 'facebook_pages', 'https://www.facebook.com/tei.thessalonikhs/'),
('ΔΙΠΑΕ Μηχανικών Πληροφορικής και Ηλεκτρονικών Συστημάτων', 'I.H.U. Information and Electronic Engineering', 'discord_servers', 'https://discord.gg/9tUnEVMe'),
('ΤΜΗΜΑ ΠΛΗΡΟΦΟΡΙΚΗΣ Α.Τ.Ε.Ι.ΤΗ.', 'A.Τ.Ε.Ι. of Thessaloniki, Department of Information Technology', 'facebook_groups', 'https://www.facebook.com/groups/pliroforikarioi/'),
('ΔΙ.ΠΑ.Ε. - Τμήμα Μηχανικών Πληροφορικής, Υπολογιστών και Τηλεπικοινωνιών', 'I.H.U. - Department of Information and Electronic Engineering', 'facebook_groups', 'https://www.facebook.com/groups/pliroforikiserron/'),
('Περιβαλλοντικη Ομαδα ΔΙΠΑΕ Θεσσαλονικης', 'Environmental group I.H.U Thessalonikis', 'facebook_groups', 'https://www.facebook.com/groups/189405949034962'),
('ΔΙΠΑΕ(Σινδος)', 'I.H.U. (Sindos)', 'facebook_groups', 'https://www.facebook.com/groups/1542744542667713');

INSERT INTO `maps` (`latitude`, `longitude`, `title_gr`, `title_en`, `description_gr`, `description_en`) VALUES
('40.65709541436208', '22.80369452293734', 'Διεθνές Πανεπιστήμιο Ελλάδος - Αλεξανδρεια Πανεπιστημιουπολη', 'International Hellenic University - Alexandria Campus', 'Το πανεπιστήμιο μας.', 'Our university'),
('40.656089735641', '22.804182812928136', 'Τμήμα ΜΠΗΣ - Κτίριο Π', 'Department ΜΠΗΣ - Building Π', 'Τμήμα Μηχανικών Πληροφορικής και Ηλεκτρονικών Συστημάτων - Κτίριο Π', 'Department of Information and Electronic Engineering - Building Π'),
('40.655602367915854', '22.805878923368827', 'Τμήμα ΜΠΗΣ - Κτίριο H', 'Department ΜΠΗΣ - Building Η', 'Τμήμα Μηχανικών Πληροφορικής και Ηλεκτρονικών Συστημάτων - Κτίριο Η', 'Department of Information and Electronic Engineering - Building Η'),
('40.655740736173236', '22.80576627059863', 'Γραμματεία τμήματος ΜΠΗΣ', 'Secretariat of the ΜΠΗΣ department ', 'Γραμματεία τμήματος Μηχανικών Πληροφορικής και Ηλεκτρονικών Συστημάτων', 'Secretariat of the Department of Information and Electronic Engineering');

INSERT INTO `offers` (`title_gr`, `title_en`, `description_gr`, `description_en`, `category`, `link`) VALUES
('Jetbrains', 'Jetbrains', 'Μια μεγάλη συλλογή από προγράμματα για προγραμματιστές με ετήσια άδεια.', 'A large collection of programs for developers with an annual license.', 'softwares', 'https://www.jetbrains.com'),
('Kivuto', 'Kivuto', 'Μια μεγάλη συλλογή από προγράμματα διάφορων εταιριών με πρόσφορες.', 'A large collection of programs of various companies with offers.', 'softwares', 'https://e5.onthehub.com/WebStore/ProductsByMajorVersionList.aspx?ws=be0fe910-869b-e011-969d-0030487d8897'),
('Microsoft', 'Microsoft', 'Μια μεγάλη συλλογή από προγράμματα της Microsoft.', 'A large collection of Microsoft programs. ', 'softwares', 'https://imselab-atei-thessaloniki.weebly.com/ms-azure-gr.html'),
('Github', 'Github', 'Μια μεγάλη συλλογή από συνδρομές και δώρα σε διάφορα προγράμματα και υπηρεσίες.', 'A large collection of subscriptions and gifts in various programs and services. ', 'softwares', 'https://education.github.com');

INSERT INTO `official_services` (`title_gr`, `title_en`, `description_gr`, `description_en`, `category`, `link`) VALUES
('Tμήμα Μηχανικών Πληροφορικής και Ηλεκτρονικών Συστημάτων', 'Department of Information and Electronic Engineering', 'Η ιστοσελίδα του τμήματος.', 'The department website.', 'department', 'https://www.iee.ihu.gr'),
('Moodle', 'Moodle', 'Ο διαδικτυακός χώρος φιλοξενήσεις μαθημάτων.', 'The web site hosting courses. ', 'department', 'https://moodle.teithe.gr/course/index.php?categoryid=125'),
('Moodle Exams', 'Moodle Exams', 'Ο διαδικτυακός χώρος για εξετάσεις μαθημάτων.', 'The web site for course exams. ', 'department', 'https://exams-iee.the.ihu.gr'),
('Ηλεκτρονικό Σύστημα Διπλωματικών', 'Electronic Diplomacy System ', 'Ανάθεση και προβολή διπλωματικών/πτυχιακών.', 'Assignment and view of diplomas/graduates.', 'department', 'https://thesis.iee.ihu.gr'),
('Δηλώσεις Μαθημάτων', 'Course Statements ', 'Δηλώσεις και προβολή μαθημάτων εξαμήνου.', 'Registration and view of semester courses', 'department', 'http://aris.noc.teithe.gr/el/diloseis'),
('Youtube', 'Youtube', 'Το Youtube του τμήματος.', 'YouTube of the department.', 'department', 'https://www.youtube.com/channel/UCq-5LWrceZMl4b5ulXF4RAg'),
('Apps', 'Apps', 'Κύριος λόγος οι ανακοινώσεις του τμήματος.', 'Main reason the announcements of the department.', 'department', 'https://apps.iee.ihu.gr'),
('Feeding', 'Feeding', 'Σύστημα Αιτήσεων Δικαιούχων Δωρεάν Σίτισης.', 'Free Feeding Application System', 'university', 'http://feeding.teithe.gr'),
('Pithia', 'Pithia', 'Κέντρο έλεγχου μαθημάτων και βαθμολόγιων φοιτητή.', 'Student control center for courses and grades.', 'department', 'http://pithia.teithe.gr/unistudent'),
('ECTS 160', 'ECTS 160', 'Έλεγχος για τον αν φοιτητής έχει συμπληρώσει τουλάχιστον 160/210 ΠΜ*', 'Check if student has completed at least 160/210 AM', 'department', 'https://www.iee.ihu.gr/ects160'),
('Διεύθυνση Τεχνικών Υπηρεσιών', 'Technical Services Department ', 'Αιτήσεις έλεγχου/επιδιόρθωσης εγκαταστάσεων και μεγάλες Αίθουσες.', 'Requests to check/repair facilities and large rooms.', 'university', 'http://dty.teithe.gr'),
('Webmail', 'Webmail', 'Το Email του τμήματος.', 'The Email of the department. ', 'department', 'https://webmail.teithe.gr'),
('Πρακτική Άσκηση', 'Internships', 'Η σελίδα για την πρακτική άσκηση των φοιτητών.', 'The student internship page.', 'department', 'http://placements.it.teithe.gr'),
('Κέντρο Δικτύου Αιτήματα', 'Network Center Requests', 'Η σελίδα του κέντρου δεκτού για σχετικά αιτήματα με τους λογαριασμούς.', 'The Admittance Center page for related requests with accounts.', 'university', 'https://helpdesk.the.ihu.gr/index.php'),
('Κεντρική Βιβλιοθήκη Πανεπιστήμιου', 'Central Library of University', 'Μπορείς να αναζητήσεις και βιβλία για αν υπάρχουν.', 'You can search for books if they exist.', 'university', 'https://www.lib.teithe.gr');

INSERT INTO `unofficial_services` (`title_gr`, `title_en`, `description_gr`, `description_en`, `creator_gr`, `creator_en`, `category`, `link`) VALUES
('Φτιάξε το πρόγραμμα του εξαμήνου σου', 'Make your semester schedule', 'Μια προσπάθεια ενός φοιτητή για να διευκολύνει την δημιουργία του εξαμηνιαίου προγράμματος.', 'An effort of a student to facilitate the creation of the semester program. ', 'Νίκος Θεοφανούδης', 'Nikos Theofanoudis ', 'department', 'https://it185181.herokuapp.com');

INSERT INTO `useful_websites` (`title_gr`, `title_en`, `description_gr`, `description_en`, `category`, `link`) VALUES
('Φοιτητικά Νέα', 'Student News', 'Ενημέρωση για όλα τα φοιτητικά νέα.', 'Information for all student news. ', 'news', 'https://www.foititikanea.gr'),
('Eduroam', 'Eduroam', 'Δωρεάν Ίντερνετ στο Campus.', 'Free Internet on Campus. ', 'internet', 'https://www.eduroam.gr'),
('Photomath', 'Photomath', 'Μια mobile εφαρμογή για να λύνεις ασκήσεις με φωτογραφίες.', 'A mobile application to solve exercises with photos.', 'maths', 'https://photomath.com'),
('Symbolab', 'Symbolab', 'Μια ιστοσελίδα για να γράφεις και να λύνεις διάφορες ασκήσεις.', 'A website to write and solve various exercises. ', 'maths', 'https://www.symbolab.com');



INSERT INTO `courses` (`title_gr`, `title_en`, `semester`, `teachers_gr`, `teachers_en`, `link`) VALUES
('Μαθηματικά Ι', 'Mathematics Ι','1o','Αντωνίου Ευστάθιος, Τζέκης Παναγιώτης', 'Antoniou Efstathios, Tzekis Panagiotis', 'course/1101'),
('Δομημένος Προγραμματισμός', 'Structured Programming','1o','Γουλιάνας Κωνσταντίνος, Ουγιάρογλου Στέφανος, Ασδρέ Κατερίνα', 'Goulianas Konstantinos, Ougiaroglou Stefanos, Asdre Katerina','course/1102'),
('Εισαγωγή στην Επιστήμη των Υπολογιστών', 'Introduction to computer science', '1ο', 'Ηλιούδης Χρήστος', 'Ilioudis Christos', 'course/1103'),
('', '', '1o', '', '', ''),
('', '', '1o', '', '', ''),
('', '', '2o', '', '', ''),
('', '', '2o', '', '', ''),
('', '', '2o', '', '', ''),
('', '', '2o', '', '', ''),
('', '', '2o', '', '', ''),
('', '', '3o', '', '', ''),
('', '', '3o', '', '', ''),
('', '', '3o', '', '', ''),
('', '', '3o', '', '', ''),
('', '', '3o', '', '', ''),
('', '', '4o', '', '', ''),
('', '', '4o', '', '', ''),
('', '', '4o', '', '', ''),
('', '', '4o', '', '', ''),
('', '', '4o', '', '', ''),
('', '', '5o', '', '', ''),
('', '', '5o', '', '', ''),
('', '', '5o', '', '', ''),
('', '', '5o', '', '', ''),
('', '', '5o', '', '', ''),
('', '', '6o', '', '', ''),
('', '', '6o', '', '', ''),
('', '', '6o', '', '', ''),
('', '', '6o', '', '', ''),
('', '', '6o', '', '', ''),
('', '', '6o', '', '', ''),
('', '', '6o', '', '', ''),
('', '', '6o', '', '', ''),
('', '', '6o', '', '', ''),
('', '', '6o', '', '', ''),
('', '', '6o', '', '', ''),
('', '', '7o', '', '', ''),
('', '', '7o', '', '', ''),
('', '', '7o', '', '', ''),
('', '', '7o', '', '', ''),
('', '', '7o', '', '', ''),
('', '', '7o', '', '', ''),
('', '', '7o', '', '', ''),
('', '', '7o', '', '', ''),
('', '', '7o', '', '', ''),
('', '', '7o', '', '', ''),
('', '', '7o', '', '', ''),
('', '', '8o', '', '', ''),
('', '', '8o', '', '', ''),
('', '', '8o', '', '', ''),
('', '', '8o', '', '', ''),
('', '', '8o', '', '', ''),
('', '', '8o', '', '', ''),
('', '', '8o', '', '', ''),
('', '', '8o', '', '', ''),
('', '', '8o', '', '', ''),
('', '', '8o', '', '', ''),
('', '', '8o', '', '', ''),
('', '', '8o', '', '', ''),
('', '', '8o', '', '', ''),
('', '', '8o', '', '', ''),
('', '', '8o', '', '', ''),
('', '', '8o', '', '', ''),
('', '', '8o', '', '', ''),
('', '', '9o', '', '', ''),
('', '', '9o', '', '', ''),
('', '', '9o', '', '', ''),
('', '', '9o', '', '', ''),
('', '', '9o', '', '', ''),
('', '', '9o', '', '', ''),
('', '', '9o', '', '', ''),
('', '', '9o', '', '', ''),
('', '', '9o', '', '', ''),
('', '', '9o', '', '', ''),
('', '', '9o', '', '', ''),
('', '', '9o', '', '', ''),
('', '', '9o', '', '', ''),
('', '', '9o', '', '', ''),
('', '', '9o', '', '', ''),
('', '', '9o', '', '', ''),
('', '', '9o', '', '', ''),
('', '', '9o', '', '', ''),
('', '', '9o', '', '', ''),
('', '', '9o', '', '', ''),
('', '', '9o', '', '', ''),
('', '', '9o', '', '', ''),
('', '', '9o', '', '', ''),
('', '', '10o', '', '', '');


INSERT INTO `teachers` (`name_gr`, `name_en`, `email`, `personal_site`, `category_gr`, `category_en`, `link`) VALUES
('Αδαμίδης Παναγιώτης', 'Adamidis Panagiotis', 'adamidis@it.teithe.gr', 'https://people.iee.ihu.gr/~adamidis/', 'Μέλη Δ.Ε.Π.', 'Faculty Members', 'https://www.iee.ihu.gr/staff/adamidis-panagiotis/'),
('Βίτσας Βασίλης', 'Vitsas Vasilis', 'vitsas@it.teithe.gr', 'https://www.it.teithe.gr/~vitsas', 'Μέλη Δ.Ε.Π.', 'Faculty Members', 'https://www.iee.ihu.gr/staff/vitsas-vasilis/'),
('Δεληγιάννης Ιγνάτιος', 'Deligiannis Ignatios', 'ignatios@it.teithe.gr', 'null', 'Μέλη Δ.Ε.Π.', 'Faculty Members', 'https://www.iee.ihu.gr/staff/deligiannis-ignatios/'),
('Δέρβος Δημήτριος', 'Dervos Dimitrios', 'dad@it.teithe.gr', 'https://www.iee.ihu.gr/~dad', 'Μέλη Δ.Ε.Π.', 'Faculty Members', 'https://www.iee.ihu.gr/staff/dervos-dimitrios/'),
('Διαμαντάρας Κωνσταντίνος', 'Diamantaras Konstantinos', 'k.diamantaras@ihu.edu.gr', 'https://www.iee.ihu.gr/~kdiamant', 'Μέλη Δ.Ε.Π', 'Faculty Members', 'https://www.iee.ihu.gr/staff/diamantaras-konstantinos/'),
('Ηλιούδης Χρήστος', 'Ilioudis Christos', 'iliou@it.teithe.gr', 'https://www.it.teithe.gr/~iliou', 'Μέλη Δ.Ε.Π.', 'Faculty Members', 'https://www.iee.ihu.gr/staff/ilioudis-christos/'),
('Καζακόπουλος Αριστοτέλης', 'Kazakopoulos Aristotelis', 'kazak@el.teithe.gr', 'null', 'Μέλη Δ.Ε.Π.', 'Faculty Members', 'https://www.iee.ihu.gr/staff/kazakopoulos-aristotelis/'),
('Κιοσκερίδης Ιορδάνης', 'Kioskeridis Iordanis', 'ikiosker@ihu.gr', 'null', 'Μέλη Δ.Ε.Π.', 'Faculty Members', 'https://www.iee.ihu.gr/staff/kioskeridis-iordanis/'),
('Κώστογλου Βασίλειος', 'Kostoglou Vasilis', 'vkostogl@ihu.gr', 'https://people.iee.ihu.gr/~vkostogl/', 'Μέλη Δ.Ε.Π.', 'Faculty Members', 'https://www.iee.ihu.gr/staff/kostoglou-vasileios/'),
('Μαρμόρκος Ιωάννης', 'Marmorkos Ioannis', 'imarm@el.teithe.gr', 'null', 'Μέλη Δ.Ε.Π.', 'Faculty Members', 'https://www.iee.ihu.gr/staff/marmorkos-ioannis/'),
('Μπάμνιος Γεώργιος', 'Bamnios Georgios', 'bamnios@el.teithe.gr', 'null', 'Μέλη Δ.Ε.Π.', 'Faculty Members', 'https://www.iee.ihu.gr/staff/bamnios-georgios/'),
('Παπακώστας Δημήτριος', 'Papakostas Dimitrios', 'dpapakos@ihu.gr', 'null', 'Μέλη Δ.Ε.Π.', 'Faculty Members', 'https://www.iee.ihu.gr/staff/papakostas-dimitrios/'),
('Σαλαμπάσης Μιχάλης', 'Salampasis Michalis', 'msa@ihu.gr', 'https://www.salampasis.gr', 'Μέλη Δ.Ε.Π.', 'Faculty Members', 'https://www.iee.ihu.gr/staff/salampasis-michalis/'),
('Σταμάτης Δημοσθένης', 'Stamatis Dimosthenis', 'demos@it.teithe.gr', 'https://www.it.teithe.gr/~demos', 'Μέλη Δ.Ε.Π', 'Faculty Members', 'https://www.iee.ihu.gr/staff/stamatis-dimosthenis/'),
('Χατζημίσιος Περικλής', 'Chatzimisios Periklis', 'pchatzimisios@ihu.gr', 'https://people.iee.ihu.gr/~peris/', 'Μέλη Δ.Ε.Π.', 'Faculty Members', 'https://www.iee.ihu.gr/staff/chatzimisios-periklis/'),
('Αντωνίου Ευστάθιος', 'Antoniou Efstathios', 'antoniou@ihu.gr', 'https://www.iee.ihu.gr/~antoniou/', 'Μέλη Δ.Ε.Π.', 'Faculty Members', 'https://www.iee.ihu.gr/staff/antoniou-efstathios/'),
('Γουλιάνας Κωνσταντίνος', 'Goulianas Konstantinos', 'gouliana@it.teithe.gr', 'https://aetos.it.teithe.gr/~gouliana/', 'Μέλη Δ.Ε.Π.', 'Faculty Members', 'https://www.iee.ihu.gr/staff/goulianas-konstantinos/'),
('Ιωαννίδου Μελίνα', 'Ioannidou Melina', 'melina@ihu.gr', 'null', 'Μέλη Δ.Ε.Π.', 'Faculty Members', 'https://www.iee.ihu.gr/staff/ioannidou-melina/'),
('Ιωσηφίδης Αθανάσιος', 'Iosifidis Athanasios', 'aiosifidis@el.teithe.gr', 'null', 'Μέλη Δ.Ε.Π.', 'Faculty Members', 'https://www.iee.ihu.gr/staff/iosifidis-athanasios/'),
('Κεραμόπουλος Ευκλείδης', 'Keramopoulos Efkleidis', 'euclid@it.teithe.gr', 'https://people.iee.ihu.gr/~euclid/', 'Μέλη Δ.Ε.Π.', 'Faculty Members', 'https://www.iee.ihu.gr/staff/keramopoulos-efkleidis/'),
('Σπάσος Μιχαήλ', 'Spasos Michail', 'spasos@el.teithe.gr', 'null', 'Μέλη Δ.Ε.Π.', 'Faculty Members', 'https://www.iee.ihu.gr/staff/spasos-michail/'),
('Τζέκης Παναγιώτης', 'Tzekis Panagiotis', 'ptzekis@el.teithe.gr', 'https://aetos.it.teithe.gr/~ptzekis/', 'Μέλη Δ.Ε.Π.', 'Faculty Members', 'https://www.iee.ihu.gr/staff/tzekis-panagiotis/'),
('Κωτσάκης Ρήγας', 'Kotsakis Rigas', 'rkotsakis@gmail.com', 'null', 'Μέλη Δ.Ε.Π.', 'Faculty Members', 'https://www.iee.ihu.gr/staff/kotsakis-rigas/'),
('Σαπουνίδης Θεοδόσιος', 'Sapounidis Theodosios', 'sapounidis@ihu.gr', 'null', 'Μέλη Δ.Ε.Π.', 'Faculty Members', 'https://www.iee.ihu.gr/staff/sapounidis-theodosios/'),
('Σιδηρόπουλος Αντώνης', 'Sidiropoulos Antonis', 'asidirop@gmail.com', 'https://people.iee.ihu.gr/~asidirop/', 'Μέλη Δ.Ε.Π.', 'Faculty Members', 'https://www.iee.ihu.gr/staff/sidiropoulos-antonis-2/'),
('Χατζόπουλος Αργύριος', 'Chatzopoulos Argyrios', 'ahatz@ihu.gr', 'null', 'Μέλη Δ.Ε.Π.', 'Faculty Members', 'https://www.iee.ihu.gr/staff/chatzopoulos-argyrios/'),
('Γιακουμής Άγγελος', 'Giakoumis Angelos', 'ang1960@el.teithe.gr', 'null', 'Μέλη Δ.Ε.Π.', 'Faculty Members', 'https://www.iee.ihu.gr/staff/giakoumis-angelos/'),
('Μανάβης Χρήστος', 'Manavis Christos', 'null', 'null', 'Μέλη Δ.Ε.Π.', 'Faculty Members', 'https://www.iee.ihu.gr/staff/manavis-christos/'),
('Μπαλτατζής Δημήτριος', 'Baltatzis Dimitrios', 'null', 'null', 'Μέλη Δ.Ε.Π. άλλων τμήματων', 'Visiting Faculty Members', 'https://www.iee.ihu.gr/staff/tsirigotis-georgios/'),
('Τσιριγώτης Γεώργιος', 'Tsirigotis Georgios', 'null', 'null', 'Μέλη Δ.Ε.Π. άλλων τμήματων', 'Visiting Faculty Members', 'https://www.iee.ihu.gr/staff/tsirigotis-georgios/'),
('Αγγέλου Κωνσταντίνος', 'Angelou Konstantinos', 'kagel@admin.teithe.gr', 'null', 'Προσωπικό Ε.ΔΙ.Π.', 'Laboratory Associates ', 'https://www.iee.ihu.gr/staff/angelou-konstantinos/'),
('Αμανατιάδης Δημήτριος', 'Amanatiadis Dimitrios', 'dima@it.teithe.gr', 'https://people.iee.ihu.gr/~dima/', 'Προσωπικό Ε.ΔΙ.Π.', 'Laboratory Associates', 'https://www.iee.ihu.gr/staff/amanatiadis-dimitrios/'),
('Αμπατζής Ζαφείριος', 'Ampatzis Zafeirios', 'zafiris@el.teithe.gr', 'null', 'Προσωπικό Ε.ΔΙ.Π', 'Laboratory Associates', 'https://www.iee.ihu.gr/staff/ampatzis-zafeirios/'),
('Ασδρέ Κατερίνα', 'Asdre Katerina', 'asdre@it.teithe.gr', 'null', 'Προσωπικό Ε.ΔΙ.Π.', 'Laboratory Associates', 'https://www.iee.ihu.gr/staff/asdre-katerina/'),
('Καλλιδοπούλου Άννα-Ελένη', 'Kallidopoulou Anna-Eleni', 'null', 'null', 'Προσωπικό Ε.ΔΙ.Π.', 'Laboratory Associates ', 'https://www.iee.ihu.gr/staff/kallidopoulou-anna-eleni/'),
('Ουγιάρογλου Στέφανος', 'Ougiaroglou Stefanos', 'stoug@ihu.gr', 'https://www.iee.ihu.gr/~stoug', 'Προσωπικό Ε.ΔΙ.Π.', 'Laboratory Associates', 'https://www.iee.ihu.gr/staff/ougiaroglou-stefanos/'),
('Τσιακμάκης Κυριάκος', 'Tsiakmakis Kyriakos', 'ktsiak@physics.auth.gr', 'https://aetos.it.teithe.gr/~ktsiak/', 'Προσωπικό Ε.ΔΙ.Π.', 'Laboratory Associates', 'https://www.iee.ihu.gr/staff/tsiakmakis-kyriakos/'),
('Αβδελίδης Κωνσταντίνος', 'Avdelidis Konstantinos', 'null', 'null', 'Έκτακτο Εκπαιδευτικό Προσωπικό', 'Visiting Lecturers', 'https://www.iee.ihu.gr/staff/avdelidis-konstantinos/'),
('Ακριτίδης Λεωνίδας', 'Akritidis Leonidas', 'lakritidis@ihu.gr', 'https://people.iee.ihu.gr/~lakritidis/', 'Έκτακτο Εκπαιδευτικό Προσωπικό', 'Visiting Lecturers', 'https://www.iee.ihu.gr/staff/akritidis-leonidas/'),
('Αλεξούδη Θεόνη', 'Alexoudi Theoni', 'theoni.alex@gmail.com', 'null', 'Έκτακτο Εκπαιδευτικό Προσωπικό', 'Visiting Lecturers', 'https://www.iee.ihu.gr/staff/alexoudi-theoni/'),
('Αρβανίτου Ελβίρα Μαρία', 'Arvanitou Elvira Maria', 'null', 'null', 'Έκτακτο Εκπαιδευτικό Προσωπικό', 'Visiting Lecturers ', 'https://www.iee.ihu.gr/staff/arvanitou-elvira-maria/'),
('Βάσσιος Βασίλειος', 'Vassios Vasileios', 'null', 'null', 'Έκτακτο Εκπαιδευτικό Προσωπικό', 'Visiting Lecturers', 'https://www.iee.ihu.gr/staff/vassios-vasileios/'),
('Βολιώτη Χριστίνα', 'Volioti Christina', 'null', 'null', 'Έκτακτο Εκπαιδευτικό Προσωπικό', 'Visiting Lecturers', 'https://www.iee.ihu.gr/staff/volioti-christina/'),
('Γεωργούδας Ιωακείμ', 'Georgoudas Ioakeim', 'mgeorgoudas@gmail.com', 'null', 'Έκτακτο Εκπαιδευτικό Προσωπικό', 'Visiting Lecturers', 'https://www.iee.ihu.gr/staff/georgoudas-ioakeim/'),
('Δελημαράς Βασίλειος', 'Delimaras Vasileios', 'null', 'null', 'Έκτακτο Εκπαιδευτικό Προσωπικό', 'Visiting Lecturers', 'https://www.iee.ihu.gr/staff/delimaras-vasileios/'),
('Δημητριάδης Παναγιώτης', 'Dimitriadis Panagiotis', 'panosdimel@gmail.com', 'null', 'Έκτακτο Εκπαιδευτικό Προσωπικό', 'Visiting Lecturers', 'https://www.iee.ihu.gr/staff/dimitriadis-panagiotis/'),
('Διαμαντουλάκης Παναγιώτης', 'Diamantoulakis Panagiotis', 'null', 'null', 'Έκτακτο Εκπαιδευτικό Προσωπικό', 'Visiting Lecturers', 'https://www.iee.ihu.gr/staff/diamantoulakis-panagiotis/'),
('Καπλάνογλου Παντελής', 'Kaplanoglou Pantelis', 'pikaplanoglou@it.teithe.gr', 'null', 'Έκτακτο Εκπαιδευτικό Προσωπικό', 'Visiting Lecturers', 'https://www.iee.ihu.gr/staff/kaplanoglou-pantelis/'),
('Κασδερίδης Στάθης', 'Kasderidis Stathis', 'kas-ihu@novocaptis.com', 'null', 'Έκτακτο Εκπαιδευτικό Προσωπικό', 'Visiting Lecturers', 'https://www.iee.ihu.gr/staff/kasderidis-stathis/'),
('Λαμπρόπουλος Γεώργιος', 'Lampropoulos Georgios', 'glampropoulos@it.teithe.gr', 'null', 'Έκτακτο Εκπαιδευτικό Προσωπικό', 'Visiting Lecturers', 'https://www.iee.ihu.gr/staff/lampropoulos-georgios/'),
('Μεσοδιακάκη Αγάπη', 'Mesodiakaki Agapi', 'null', 'https://sites.google.com/site/agapimesodiakaki', 'Έκτακτο Εκπαιδευτικό Προσωπικό', 'Visiting Lecturers', 'https://www.iee.ihu.gr/staff/mesodiakaki-agapi/'),
('Μηλιώτης Βασίλης', 'Miliotis Vasilis', 'null', 'null', 'Έκτακτο Εκπαιδευτικό Προσωπικό', 'Visiting Lecturers', 'https://www.iee.ihu.gr/staff/miliotis-vasilis/'),
('Μπαργούλη Μαρίσα', 'Bargouli Marisa', 'null', 'null', 'Έκτακτο Εκπαιδευτικό Προσωπικό', 'Visiting Lecturers', 'https://www.iee.ihu.gr/staff/bargouli-marisa/'),
('Παπαγεωργίου Δημήτριος', 'Papageorgiou Dimitrios', 'dimpapag@ece.auth.gr', 'https://arl.ee.auth.gr/people/papageorgiou', 'Έκτακτο Εκπαιδευτικό Προσωπικό', 'Visiting Lecturers', 'https://www.iee.ihu.gr/staff/papageorgiou-dimitrios/'),
('Παπαδοπούλου Μαρία', 'Papadopoulou Maria', 'mpapa@el.teithe.gr', 'null', 'Έκτακτο Εκπαιδευτικό Προσωπικό', 'Visiting Lecturers', 'https://www.iee.ihu.gr/staff/papadopoulou-maria/'),
('Σαρηγιαννίδης Αντώνης', 'Sarigiannidis Antonis', 'null', 'null', 'Έκτακτο Εκπαιδευτικό Προσωπικό', 'Visiting Lecturers', 'https://www.iee.ihu.gr/staff/sarigiannidis-antonis/'),
('Τεκτονίδης Δημήτριος', 'Tektonidis Dimitrios', 'null', 'null', 'Έκτακτο Εκπαιδευτικό Προσωπικό', 'Visiting Lecturers ', 'https://www.iee.ihu.gr/staff/tektonidis-dimitrios/'),
('Τοκατλίδης Χρήστος', 'Tokatlidis Christos', 'dtektoni@it.teithe.gr', 'https://aetos.it.teithe.gr/~dtektoni', 'Έκτακτο Εκπαιδευτικό Προσωπικό', 'Visiting Lecturers', 'https://www.iee.ihu.gr/staff/tokatlidis-christos/'),
('Τσελεγκαρίδης Σωκράτης', 'Tselegkaridis Sokratis', 'sok.tsele@gmail.com', 'null', 'Έκτακτο Εκπαιδευτικό Προσωπικό', 'Visiting Lecturers', 'https://www.iee.ihu.gr/staff/tselegkaridis-sokratis/'),
('Τσιρογιάννης Ανδρέας', 'Tsirogiannis Andreas', 'null', 'null', 'Έκτακτο Εκπαιδευτικό Προσωπικό', 'Visiting Lecturers ', 'https://www.iee.ihu.gr/staff/tsirogiannis-andreas/');
